name: Cypress Testing

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  run-cypress:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: npm run build

      - name: Start Preview
        run: npm run preview
