name : Cypress Testing

on:
  push:
    branches: [main]
  pull_request:
      branches: [main]

jobs:
  
  runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cypress run
      uses: cypress-io/github-action@v6
      with: 
        build: npm run build
        start: npm run preview
